

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "telefone": "949036363",
  "senha": "1234"
}
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMjhiMjBmOC0xMTJlLTQ5NWItOWJmNC0zZWQwMzQ3YjIyZGQiLCJwcm9maWxlIjoiQ0xJRU5UIiwiaWF0IjoxNzUxMzg1NTE0LCJleHAiOjE3NTE0NzE5MTR9.yonVq5x-JBQ8NyGsagV-SrIlhJh2xSam9FWqryZ3zs4

### Logout
POST  http://localhost:3000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWIxNjkxZi0xMTY2LTRkZWUtODkxNi0wNDlmMmRkYTlhYWEiLCJlbWFpbCI6Ijk0OTAzNjM2MyIsImlhdCI6MTc3ODkyMTU3OSwiZXhwIjoxNzc4OTIyNDc5fQ.aggQR6JnxJvU7AP8NCogUAmvcMSEo2Y-ldt07lZ22CY