

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "telefone": "929564424",
  "senha": "1234"
}
#Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMjhiMjBmOC0xMTJlLTQ5NWItOWJmNC0zZWQwMzQ3YjIyZGQiLCJwcm9maWxlIjoiQ0xJRU5UIiwiaWF0IjoxNzUxMzg1NTE0LCJleHAiOjE3NTE0NzE5MTR9.yonVq5x-JBQ8NyGsagV-SrIlhJh2xSam9FWqryZ3zs4

### Logout
POST  http://localhost:3000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTNjMWMyYi02MmFhLTRiOGMtOTAwMy0yZWRhYWZhMzM1OTQiLCJlbWFpbCI6IjkyOTU2NDQyNCIsImlhdCI6MTc3OTAwNDE0NSwiZXhwIjoxNzc5MDA1MDQ1fQ.hthUwkeE7kpFw3n9IxDByjbvrXuHUztdlMEaxBwOJDM